### ISSUE TITLE
product_plot.html: line lengths.

### ISSUE THREAD

**Issue by AndreaAguadoM** [m-crown/SPEAR-Reports#10]
Hello! My name is Andrea and I am a Spanish bioinformatician. Currently, I am using Spear as one of the main tools within my study in order to obtain valuable results. Specifically, when analyziing the product_plot outputs, which are contained within the product_plots output directory, the following question comes to my mind: 
Within this images, every mutation has associated a specific length for the line which links them to the protein representation. I have also observed how this line length tends to decrease as the gene position increases. What does this length specifically mean? In the following image the lines that I mentioned are better identified: 

![My project-1(1)](https://user-images.githubusercontent.com/96059122/197709741-aae56fed-3df0-4a94-af94-4b1af5e4e595.png)

**Comment by m-crown** [comment]
Hi Andrea, the line length varies purely to distinguish mutations from one another on parts of the plot where there are a lot of mutations close together (e.g. spike) - it has no functional meaning and is purely aesthetic. In the future we may change this to include some meaning, if we do this we will be sure to document it, but for now you can ignore it.
